### ISSUE TITLE
Octane simulation / system creation - No template found, topology missing atoms or wrong forcefield

### ISSUE THREAD

**Issue by kadiliissaar** [openmm/openmmforcefields#140]
Hello!

I am trying to run the following simulation but getting the following error while creating the system. Can anyone recommend please what the problem may be? The pdb file is here: 
https://drive.google.com/file/d/1DBMndqQYN7exj4wQ1K_FNIOmC6cNYAa_/view?usp=sharing

Thank you and best wishes,
Kadi

from simtk.openmm.app import PDBFile
from openforcefield.topology import Molecule
from openmmforcefields.generators import GAFFTemplateGenerator
from simtk.openmm.app import ForceField

molecule = Molecule.from_smiles('CCCCCCCC')
gaff = GAFFTemplateGenerator(molecules=molecule)
forcefield = ForceField()
forcefield.registerTemplateGenerator(gaff.generator)
pdbfile = PDBFile('packed_box_octane.pdb')
system = forcefield.createSystem(pdbfile.topology)

**ValueError:** No template found for residue 1 (OCT).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.

**Comment by jchodera** [comment]
The [PDB Specification](http://www.wwpdb.org/documentation/file-format) requires that nonstandard residues use the [`HETATM`](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM) record and include [`CONECT`](http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT) records that define connectivity between nonstandard atoms. The reason for this is that there is absolutely no way to infer what the connectivity in your molecules are otherwise. Can you try again with a PDB conformant file?

**Comment by kadiliissaar** [comment]
This makes sense - thank you, John! I have been using packmol to create the pdb file and it seems their output does not follow these specifications even when the input does (in particular, the connectivity information goes missing...). But I can see now that simulation working on a file that has the right PDB specification, so I think I can get this packed box also to work after the connectivities get included. Thank you again!

**Comment by jchodera** [comment]
@kadiliissaar : I've opened an issue in the packmol source repo to see if this is something easy to add:
https://github.com/m3g/packmol/issues/23

**Comment by lmiq** [comment]
Yes, it is easy. Just give a couple of days, as soon as I have a window I will implement that.

**Comment by jchodera** [comment]
Awesome! Enormous thanks @lmiq!

**Comment by kadiliissaar** [comment]
That'd be fantastic, thank you both!

**Comment by lmiq** [comment]
Dear @kadiliissaar , I have implemented the reading and writing of the CONECT field. I think it is working properly. However, I would be grateful if you could test the master version before I release it as a new stable version. Please download it from here:

https://github.com/m3g/packmol/archive/master.zip

Let me know if this version reads and writes the fields properly in your case. 

One detail: since the PDB format is strict, if the atom indexes are greater than 99999 then numbers are printed in hexadecimal format. I am not sure which packages are able to deal with this, which are not. VMD, for instance, deals with these numbers well, Pymol does not (and, for instance, draws the connectivity wrongly in this case). 

Install and run with:
```

unzip packmol-master.zip
cd packmol-master
make
packmol < example.inp

```

**Comment by peastman** [comment]
Various programs use different approaches to work around the atom limit, all of which are hacks to one extent or another.  The best solution, if it's possible, is to use PDBx/mmCIF instead, which doesn't have that limit.

**Comment by lmiq** [comment]
Yes, support for mmCIF is something that I need to implement at some point. I didn't do that yet because the simulation packages I have experience with simply ignore the indexes, I never had someone asking me to support those files except for some trivial visualization problem. By the way, the files can be read with VMD (with the hexadecimal numbering) and saved in other formats if desired (I am mentioning this as a possible workaround for the moment).

**Comment by kadiliissaar** [comment]
> Dear @kadiliissaar , I have implemented the reading and writing of the CONECT field. I think it is working properly. However, I would be grateful if you could test the master version before I release it as a new stable version. Please download it from here:
> 
> https://github.com/m3g/packmol/archive/master.zip
> 
> Let me know if this version reads and writes the fields properly in your case.
> 
> One detail: since the PDB format is strict, if the atom indexes are greater than 99999 then numbers are printed in hexadecimal format. I am not sure which packages are able to deal with this, which are not. VMD, for instance, deals with these numbers well, Pymol does not (and, for instance, draws the connectivity wrongly in this case).
> 
> Install and run with:
> 
> ```
> 
> unzip packmol-master.zip
> cd packmol-master
> make
> packmol < example.inp
> ```

Hi lmiq,

I tried but got an error when running the make command:
make: /usr/bin/gfortran: No such file or directory
make: *** [sizes.o] Error 1

I'll try to see if I can get it fixed (I am on Mac OS 10.15) and get back to you then!

Best wishes,
Kadi

**Comment by kadiliissaar** [comment]
Dear Imiq,

I got this issue fixed now (had to just change to name of the directory in the make file) but the the output file doesn't include the connectivity information still! All the files are in this folder. Let me know if you have any ideas or suggestions why it doesn't work?

https://drive.google.com/drive/folders/1Q1Rc5cgDg-kkimt8e5-XQVKyoyfjs_LI?usp=sharing

Best wishes,
Kadi

**Comment by lmiq** [comment]
Dear @kadiliissaar , plase confirm that you have downloaded and are using the packmol version from the master branch link:

https://github.com/m3g/packmol/archive/master.zip

I have tested it here and it worked. I recommend you running explicitly the version downloaded, with, for instance,

`
unzip packmol-master.zip
cd packmol-master
make
`
and run it with the path to the new executable explicitly written, to avoid using an older version:
`
./packmol-master/packmol < pack_octane.inp
`

**Comment by kadiliissaar** [comment]
Dear @lmiq,

You were absolutely right - it is all working now after I fixed this, i.e. the output file looks as I expected and the following openMM simulation also works. I tried cases where up to two different types of molecules (.pdb files) were mixed.

Thanks a lot for adding this feature so quickly!

Best wishes,
Kadi

**Comment by lmiq** [comment]
Great. Thank you for the feedback. The release 20.2 of Packmol includes that new feature.
