### ISSUE TITLE
Molecule Object Automatically Adds Hydrogens to Neturalize Charge 

### ISSUE THREAD

**Issue by Dan-Burns** [openmm/openmmforcefields#175]
Hello,

I want to use the GAFF template generator for a negatively charged molecule (alpha ketoglutarate).

When create a molecule object from_file with a .mol file containing 14 atoms, the molecule object that is returned after the block including the "GAFFTemplateGenerator(molecules=akg_molecule)" gains two hydrogens to neutralize the carboxylate groups. 

I have also edited the .mol file to specifically indicate the oxygens have a -1 charge with the 
"M CHG 1 3 -1" 
blocks at the end of the file.

Every time I create the gaff object regardless of input file type, it returns a molecule with 2 additional hydrogens.

When I try from_smiles, the template that is generated apparently has a bond between the two terminal carboxylate singly bonded oxygens and the resulting molecule appears as a ring when visualized.
C(CC(=O)O-1)C(=O)C(=O)O-1

How can I go about generating the template with the correct bonds and charges?

Thank you,

Dan

**Comment by peastman** [comment]
Did you intend to close this?  Did you figure it out?

**Comment by Dan-Burns** [comment]
I was able to get the gaff template generator to produce the right template but I don't seem to be able to combine all of the molecules into a single pdb file that the forcefield will accept.  The conect records that are generated when I save the complex in pymol to a pdb aren't correct.

I have DNA that has the correct residue names according to the forcefield, why do I need conect records for those?

My small molecule that I generated parameters for isn't recognized either.

Thought I was in the clear after the gaff issue.

Thanks,

Dan

**Comment by jchodera** [comment]
@Dan-Burns : Can you post the input file you're using that defines the 14-atom system you want to simulate and whether you have the OpenEye toolkit installed (or are using the default RDKit backend instead)? I'm unfamiliar with `.mol` files---the [OpenFF Toolkit](https://github.com/openforcefield/openff-toolkit) mainly intends to support SDF files---but this could be an OpenFF toolkit issue.

Starting from SMILES is problematic unless you tag the index of each atom in the SMILES string (as in SMIRKS), since the atom order is arbitrary in a SMILES string otherwise. What is likely happening there is that the molecule being created has a different atom order than the atoms in your system, and no effort is made to try to do correspondence matching.

We need to find a way to read a molecule that contains the unambiguous molecular topology information into the `Molecule` object for this to work for you, so let's focus on what format(s) you have available and what might be going wrong in `Molecule.from_file()`.

**Comment by jchodera** [comment]
> Is it possible to add separate topologies into one system? It would be easier to have each molecule as it's own pdb file and then combine them in openmm.

You _can_ use `openmm.app.Modeller` to combine `Topology` objects in OpenMM!
http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller

See [`Modeller.add()`](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.add).

**Comment by Dan-Burns** [comment]
Wow - thank you!  I ended up getting the 14 atom ligand sorted out earlier after making that edit to the mol file.  I looked at the wrong object before I posted the first comment.  

Modeller.add() saved my weekend!

Thank you,

Dan
