### ISSUE TITLE
parmchk2 fails to run if openmmforcefields is installed somewhere with spaces in the path

### ISSUE THREAD

**Issue by rosemary-cresset** [openmm/openmmforcefields#215]
If the GAFF dat file is located somewhere with spaces in the path, as is common on Windows, the parmchk2 command from template_generators.py does not work. Adding quotes around the file path didn't help, but I found it could be fixed by copying the GAFF dat file to the temporary directory and passing that to parmchk2 instead.

**Comment by jchodera** [comment]
Thanks for the very detailed bug report!

We don't officially support win because [AmberTools is not available on
conda-forge for win](https://anaconda.org/conda-forge/ambertools/files),
but we'd be happy to consider a contributed PR that would fix the win
behavior!

In general, we are happy to quickly review contributed PR if any of these
issues are easy to fix on your end.

**Comment by rosemary-cresset** [comment]
Thank you, I have done just that, also for #214 and #216. :-) It will make life a lot easier for us if we don't have to patch these fixes in during our build process.
